x-dvirtd:
  cmdopt: useview,usedir
  ports: 3000,5173,8000,8080,5000,4173

services:
  devel-mirror:
    image: ${REGISTRY}/mirror:${MIRROR_VERSION}
    extends:
      file: builder.yml
      service: devel-builder
    build:
      context: .
      dockerfile: images/mirror.dockerfile
      args:
        - BUILDER_VERSION=${BUILDER_VERSION}
    environment:
      - DISPLAY=${APPDISPLAY:-}
      - ENTRY_APP=${ENTRY_APP:-kitty}
    user: archlinux
    container_name: "devel-mirror"
