x-dvirtd:
  cmdopt: useview,usedir

services:
  devel-${IMAGE}:
    image: ${REGISTRY}/${IMAGE}:${VERSION}
    extends:
      file: mirror.yml
      service: devel-mirror
    build:
      context: .
      dockerfile: images/${IMAGE}.dockerfile
      args:
        - MIRROR_VERSION=${MIRROR_VERSION}
        - BUILDER_VERSION=${BUILDER_VERSION}
    user: archlinux
    container_name: "devel-${IMAGE}"
